CREATE TABLE public.channels (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    is_monetized boolean NOT NULL,
    name character varying(255),
    total_like_count integer NOT NULL,
    total_subs integer NOT NULL,
    total_views integer NOT NULL,
    updated_at timestamp(6) without time zone,
    watch_hours double precision,
    user_id uuid
);
CREATE TABLE public.channels_subscribers (
    channel_id uuid NOT NULL,
    subscriber_id uuid NOT NULL
);
CREATE TABLE public.playlists (
    id uuid NOT NULL,
    name character varying(255),
    channel_id uuid
);
CREATE TABLE public.playlists_videos (
    playlist_id uuid NOT NULL,
    video_id character varying(255) NOT NULL
);
CREATE TABLE public.tags (
    id uuid NOT NULL,
    name character varying(255)
);
CREATE TABLE public.user_tag_history (
    id integer NOT NULL,
    count integer NOT NULL,
    last_watched timestamp(6) without time zone,
    tag_id uuid,
    user_id uuid
);
ALTER TABLE public.user_tag_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_tag_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.user_watch_history (
    id integer NOT NULL,
    count integer NOT NULL,
    is_liked boolean NOT NULL,
    last_watched timestamp(6) without time zone,
    user_id uuid,
    video_id character varying(255)
);
ALTER TABLE public.user_watch_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_watch_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.users (
    id uuid NOT NULL,
    country character varying(255),
    created_at timestamp(6) without time zone,
    dob date,
    email character varying(255),
    gender character varying(255),
    name character varying(255),
    password character varying(255),
    phone_number bigint,
    updated_at timestamp(6) without time zone
);
CREATE TABLE public.videos (
    id character varying(255) NOT NULL,
    description character varying(255),
    name character varying(255),
    thumbnail_link character varying(255),
    updated_at timestamp(6) without time zone,
    upload_date_time timestamp(6) without time zone,
    video_link character varying(255),
    views integer NOT NULL,
    channel_id uuid
);
CREATE TABLE public.videos_tags (
    video_id character varying(255) NOT NULL,
    tag_id uuid NOT NULL
);
ALTER TABLE ONLY public.channels
    ADD CONSTRAINT channels_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.channels_subscribers
    ADD CONSTRAINT channels_subscribers_pkey PRIMARY KEY (channel_id, subscriber_id);
ALTER TABLE ONLY public.playlists
    ADD CONSTRAINT playlists_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.playlists_videos
    ADD CONSTRAINT playlists_videos_pkey PRIMARY KEY (playlist_id, video_id);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.videos_tags
    ADD CONSTRAINT videos_tags_pkey PRIMARY KEY (video_id, tag_id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);
ALTER TABLE ONLY public.tags
    ADD CONSTRAINT ukt48xdq560gs3gap9g7jg36kgc UNIQUE (name);
ALTER TABLE ONLY public.user_tag_history
    ADD CONSTRAINT user_tag_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_watch_history
    ADD CONSTRAINT user_watch_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.videos
    ADD CONSTRAINT videos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.channels_subscribers
    ADD CONSTRAINT fk3s8epg3abry5k3lmoyxwa986e FOREIGN KEY (subscriber_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.videos_tags
    ADD CONSTRAINT fk6dmqp9j7nblfmwejlinc56brp FOREIGN KEY (video_id) REFERENCES public.videos(id);
ALTER TABLE ONLY public.playlists_videos
    ADD CONSTRAINT fk8qba2oq2538waetokf0392rkm FOREIGN KEY (video_id) REFERENCES public.videos(id);
ALTER TABLE ONLY public.playlists_videos
    ADD CONSTRAINT fkap38ejwasr5liwju3ld0infsw FOREIGN KEY (playlist_id) REFERENCES public.playlists(id);
ALTER TABLE ONLY public.videos
    ADD CONSTRAINT fkbaube8rnq6coeqb22rt2fv8hh FOREIGN KEY (channel_id) REFERENCES public.channels(id);
ALTER TABLE ONLY public.videos_tags
    ADD CONSTRAINT fkbgf46f996psn498mo5sxh48sg FOREIGN KEY (tag_id) REFERENCES public.tags(id);
ALTER TABLE ONLY public.channels
    ADD CONSTRAINT fki78dq62d5f9wn545wcdl4kohf FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.playlists
    ADD CONSTRAINT fkj3jufp2nfy3w2murrds06232l FOREIGN KEY (channel_id) REFERENCES public.channels(id);
ALTER TABLE ONLY public.channels_subscribers
    ADD CONSTRAINT fkld3cp5io1lm7h89y22li0h8la FOREIGN KEY (channel_id) REFERENCES public.channels(id);
