spring.application.name=video-service
server.port=${PORT:${SERVER_PORT:8083}}

image.url.endpoint=${IMAGE_URL:http://localhost:8080}
image.private.key=${IMAGE_PRIVATE_KEY:}
image.public.key=${IMAGE_PUBLIC_KEY:}

spring.servlet.multipart.max-file-size=${MAX_UPLOAD_FILE_SIZE:500MB}
spring.servlet.multipart.max-request-size=${MAX_UPLOAD_REQUEST_SIZE:500MB}
central.api.url=${CENTRAL_API_URL:http://localhost:8084/api/v1/central}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:8080,http://localhost:5173}
app.docs.external-url=${APP_DOCS_EXTERNAL_URL:https://docs.streamsphere.com/video}

springdoc.swagger-ui.path=${SWAGGER_UI_PATH:/swagger-ui.html}
springdoc.api-docs.path=${API_DOCS_PATH:/v3/api-docs}

management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_EXPOSE:health,info}
management.endpoint.health.probes.enabled=true

# Redis Configuration
#spring.data.redis.host=localhost
#spring.data.redis.port=6379
#spring.data.redis.password=   # keep blank if no password is set
#spring.data.redis.timeout=60000
